### PR TITLE
fix docstring of split.py

### LINKED ISSUE #69: Question about docstring
https://github.com/nyanp/nyaggle/blob/d5dd9cf387def52a41bfb4d15fc07195fb9392c7/nyaggle/validation/split.py#L69

This `split`  should be `folds` ?

### PR DESCRIPTION
**Pull request by tenajima**
fix #69

### CODE REVIEW

**Comment by nyanp** [comment]
@harupy LGTM 👍 Thanks!!

**Comment by harupy** [comment]
@nyanp  This isn't my PR 😂

**Comment by tenajima** [comment]
I was confused 😂
You did great job on atma cup!

**Comment by nyanp** [comment]
oops, I’m very sorry… @tenajima Thanks very much for your PR!

**Pull request merged**
